# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53564e0426720aa358e181588f0f6e8d57e0558e686cf4e92ff29a248d05f23f83c87c7809fad80f20b2080fe44a603b55fd1e8ef73ca433d5d0c372d01d4ea6

test:
  secret_key_base: c286d03bff065cd089a9a295558966f65d7d85a1de56cfe159dd9e37ccdc17c1f2723658ce5a15e0d6c726057d331123478321d09737b3430c474c86b252162a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
